# -*- coding: utf-8 -*-

###
### This file is generated automatically by SALOME v8.3.0 with dump python functionality
###

import os
import sys #
import salome

salome.salome_init()
theStudy = salome.myStudy

import salome_notebook
pwd = os.getcwd()
print("Current path is {}".format(pwd))
notebook = salome_notebook.NoteBook(theStudy) #
sys.path.insert(0, pwd)
meshname = 'study_mobini2017_mesh'

### geometry parameters###
r_el = 0.0005
r_well = 0.0346
h_well = 0.01705
h_el = 0.001
dist_el = 0.022
####################################################
##       Begin of NoteBook variables section      ##
####################################################
notebook.set("r_well", r_well)
notebook.set("r_well_half", "r_well/2.")
notebook.set("r_well_half_n", "-r_well_half")
notebook.set("h_well", h_well)
notebook.set("h_liquid", "h_well*0.8")
notebook.set("h_air", "h_well*2.")
notebook.set("h_el", h_el)
notebook.set("r_el", r_el)
notebook.set("l_el", "r_well")
notebook.set("dist_el", dist_el)
notebook.set("dist_el_center", "dist_el/2.+r_el")
notebook.set("dist_el_center_n", "-dist_el_center")
notebook.set("h_up", "h_air-h_el")
notebook.set("r_el_n", "-r_el")
notebook.set("outer_fuse", "-0.5*(r_well+h_el)")
####################################################
##        End of NoteBook variables section       ##
####################################################
###
### GEOM component
###

import GEOM
from salome.geom import geomBuilder
import math
import SALOMEDS


geompy = geomBuilder.New(theStudy)

O = geompy.MakeVertex(0, 0, 0)
OX = geompy.MakeVectorDXDYDZ(1, 0, 0)
OY = geompy.MakeVectorDXDYDZ(0, 1, 0)
OZ = geompy.MakeVectorDXDYDZ(0, 0, 1)
Cylinder_1 = geompy.MakeCylinderRH("r_well", "h_liquid")
Cylinder_1_face_10 = geompy.GetSubShape(Cylinder_1, [10])
Vertex_1 = geompy.MakeVertexOnSurface(Cylinder_1_face_10, 0.5, 0.5)
geomObj_1 = geompy.GetSubShape(Cylinder_1, [10])
Vector_Normal_1 = geompy.GetNormal(geomObj_1, Vertex_1)
Cylinder_2 = geompy.MakeCylinder(Vertex_1, Vector_Normal_1, "r_well", "h_air")
geomObj_2 = geompy.MakeVertex(0.0173, -0.0173, 0.001)
geomObj_3 = geompy.MakeVertex(-0.0173, -0.0173, 0.001)
geomObj_4 = geompy.MakeVertex(-0.0173, 0.0173, 0.001)
geomObj_5 = geompy.MakeVertex(0.0173, 0.0173, 0.001)
Line_1 = geompy.MakeLineTwoPnt(geomObj_2, geomObj_3)
geomObj_6 = geompy.MakeLineTwoPnt(geomObj_4, geomObj_5)
geomObj_7 = geompy.MakeCylinder(geomObj_2, Line_1, 0.0005, 0.0173)
geomObj_8 = geompy.MakeCylinder(geomObj_4, geomObj_6, 0.0005, 0.0173)
Line_2 = geompy.MakeLineTwoPnt(geomObj_5, geomObj_4)
geomObj_9 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_10 = geompy.MakeCircle(geomObj_2, Line_1, 0.0005)
geomObj_11 = geompy.MakeCircle(geomObj_3, Line_1, 0.0005)
geomObj_12 = geompy.MakeCircle(geomObj_4, Line_2, 0.0005)
geomObj_13 = geompy.MakeCircle(geomObj_5, Line_2, 0.0005)
geomObj_14 = geompy.MakeVertex(-0.0178, 0.0173, 0.01364)
Vector_1 = geompy.MakeVectorDXDYDZ(0, 0, 1)
Vertex_2 = geompy.MakeVertex("dist_el_center_n", "dist_el_center_n", "h_el")
Vertex_3 = geompy.MakeVertex("dist_el_center_n", "dist_el_center", "h_el")
Cylinder_3 = geompy.MakeCylinder(Vertex_2, Vector_1, "r_el", "h_up")
Cylinder_4 = geompy.MakeCylinder(Vertex_3, Vector_1, "r_el", "h_up")
Vector_2 = geompy.MakeVectorDXDYDZ(1, 0, 0)
Cylinder_5 = geompy.MakeCylinder(Vertex_2, Vector_2, "r_el", "l_el")
Cylinder_6 = geompy.MakeCylinder(Vertex_3, Vector_2, "r_el", "l_el")
Translation_1 = geompy.MakeTranslation(Cylinder_3, 0, 0, "r_el_n")
Translation_2 = geompy.MakeTranslation(Cylinder_4, 0, 0, "r_el_n")
Fuse_1 = geompy.MakeFuseList([Cylinder_6, Translation_2], True, True)
Fuse_2 = geompy.MakeFuseList([Cylinder_5, Translation_1], True, True)
Partition_1 = geompy.MakePartition([Cylinder_1, Cylinder_2], [], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
Cut_1 = geompy.MakeCutList(Partition_1, [Fuse_1, Fuse_2], True)
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["VERTEX"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["VERTEX"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["VERTEX"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["VERTEX"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["SOLID"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
listSubShapeIDs = geompy.SubShapeAllIDs(Cut_1, geompy.ShapeType["FACE"])
OuterIsolation = geompy.CreateGroup(Cut_1, geompy.ShapeType["FACE"])
geompy.UnionIDs(OuterIsolation, [76, 71, 11, 4])
Contact1 = geompy.CreateGroup(Cut_1, geompy.ShapeType["FACE"])
geompy.UnionIDs(Contact1, [33, 55, 60, 65, 67, 83, 90])
Contact2 = geompy.CreateGroup(Cut_1, geompy.ShapeType["FACE"])
geompy.UnionIDs(Contact2, [21, 45, 50, 78, 88])
Medium = geompy.CreateGroup(Cut_1, geompy.ShapeType["SOLID"])
geompy.UnionIDs(Medium, [2])
Air = geompy.CreateGroup(Cut_1, geompy.ShapeType["SOLID"])
geompy.UnionIDs(Air, [69])
geompy.DifferenceIDs(Contact1, [33, 55, 60, 65, 67, 83, 90])
geompy.UnionIDs(Contact1, [33, 55, 60, 67, 83, 90])
geompy.DifferenceIDs(Contact2, [21, 45, 50, 78, 88])
geompy.UnionIDs(Contact2, [21, 45, 50, 78, 88, 65])
geompy.addToStudy( O, 'O' )
geompy.addToStudy( OX, 'OX' )
geompy.addToStudy( OY, 'OY' )
geompy.addToStudy( OZ, 'OZ' )
geompy.addToStudy( Cylinder_1, 'Cylinder_1' )
geompy.addToStudyInFather( Cylinder_1, Cylinder_1_face_10, 'Cylinder_1:face_10' )
geompy.addToStudy( Vertex_1, 'Vertex_1' )
geompy.addToStudy( Vector_Normal_1, 'Vector_Normal_1' )
geompy.addToStudy( Cylinder_2, 'Cylinder_2' )
geompy.addToStudy( Line_1, 'Line_1' )
geompy.addToStudy( Line_2, 'Line_2' )
geompy.addToStudy( Vector_1, 'Vector_1' )
geompy.addToStudy( Vertex_2, 'Vertex_2' )
geompy.addToStudy( Vertex_3, 'Vertex_3' )
geompy.addToStudy( Cylinder_3, 'Cylinder_3' )
geompy.addToStudy( Cylinder_4, 'Cylinder_4' )
geompy.addToStudy( Vector_2, 'Vector_2' )
geompy.addToStudy( Cylinder_5, 'Cylinder_5' )
geompy.addToStudy( Cylinder_6, 'Cylinder_6' )
geompy.addToStudy( Translation_1, 'Translation_1' )
geompy.addToStudy( Translation_2, 'Translation_2' )
geompy.addToStudy( Fuse_1, 'Fuse_1' )
geompy.addToStudy( Fuse_2, 'Fuse_2' )
geompy.addToStudy( Partition_1, 'Partition_1' )
geompy.addToStudy( Cut_1, 'Cut_1' )
geompy.addToStudyInFather( Cut_1, OuterIsolation, 'OuterIsolation' )
geompy.addToStudyInFather( Cut_1, Contact1, 'Contact1' )
geompy.addToStudyInFather( Cut_1, Contact2, 'Contact2' )
geompy.addToStudyInFather( Cut_1, Medium, 'Medium' )
geompy.addToStudyInFather( Cut_1, Air, 'Air' )

###
### SMESH component
###

import  SMESH, SALOMEDS
from salome.smesh import smeshBuilder

smesh = smeshBuilder.New(theStudy)
smeshObj_1 = smesh.Mesh(Cut_1)
NETGEN_1D_2D_3D = smesh.CreateHypothesis('NETGEN_2D3D', 'libNETGENEngine.so')
status = smeshObj_1.AddHypothesis(NETGEN_1D_2D_3D)
NETGEN_3D_Parameters_1 = smesh.CreateHypothesis('NETGEN_Parameters', 'libNETGENEngine.so')
status = smeshObj_1.AddHypothesis(NETGEN_3D_Parameters_1)
NETGEN_3D_Parameters_1.SetMaxSize( 0.0108887 )
NETGEN_3D_Parameters_1.SetSecondOrder( 0 )
NETGEN_3D_Parameters_1.SetOptimize( 1 )
NETGEN_3D_Parameters_1.SetFineness( 3 )
NETGEN_3D_Parameters_1.SetMinSize( 0 )
NETGEN_3D_Parameters_1.SetUseSurfaceCurvature( 1 )
NETGEN_3D_Parameters_1.SetFuseEdges( 1 )
NETGEN_3D_Parameters_1.SetQuadAllowed( 0 )
isDone = smeshObj_1.Compute()
smeshObj_2 = smeshObj_1.GroupOnGeom(OuterIsolation,'OuterIsolation',SMESH.FACE)
smeshObj_3 = smeshObj_1.GroupOnGeom(Contact1,'Contact1',SMESH.FACE)
smeshObj_4 = smeshObj_1.GroupOnGeom(Contact2,'Contact2',SMESH.FACE)
smeshObj_5 = smeshObj_1.GroupOnGeom(Medium,'Medium',SMESH.VOLUME)
smeshObj_6 = smeshObj_1.GroupOnGeom(Air,'Air',SMESH.VOLUME)
smeshObj_7 = smeshObj_1.GroupOnGeom(OuterIsolation,'OuterIsolation',SMESH.NODE)
smeshObj_8 = smeshObj_1.GroupOnGeom(Contact1,'Contact1',SMESH.NODE)
smeshObj_9 = smeshObj_1.GroupOnGeom(Contact2,'Contact2',SMESH.NODE)
smeshObj_10 = smeshObj_1.GroupOnGeom(Medium,'Medium',SMESH.NODE)
smeshObj_11 = smeshObj_1.GroupOnGeom(Air,'Air',SMESH.NODE)
smesh.SetName(smeshObj_1, 'Mesh_1')
try:
  smeshObj_1.ExportMED(pwd + '/' + str(meshname) + '.med', 0, SMESH.MED_V2_2, 1, None ,1)
  pass
except:
  print 'ExportToMEDX() failed. Invalid file name?'
smeshObj_1.RemoveGroupWithContents( smeshObj_2 )
smeshObj_1.RemoveGroupWithContents( smeshObj_3 )
smeshObj_1.RemoveGroupWithContents( smeshObj_4 )
smeshObj_1.RemoveGroupWithContents( smeshObj_5 )
smeshObj_1.RemoveGroupWithContents( smeshObj_6 )
smeshObj_12 = smeshObj_1.GroupOnGeom(OuterIsolation,'OuterIsolation',SMESH.FACE)
smeshObj_13 = smeshObj_1.GroupOnGeom(Contact1,'Contact1',SMESH.FACE)
smeshObj_14 = smeshObj_1.GroupOnGeom(Contact2,'Contact2',SMESH.FACE)
smeshObj_15 = smeshObj_1.GroupOnGeom(Medium,'Medium',SMESH.VOLUME)
smeshObj_16 = smeshObj_1.GroupOnGeom(Air,'Air',SMESH.VOLUME)
smeshObj_17 = smeshObj_1.GroupOnGeom(OuterIsolation,'OuterIsolation',SMESH.NODE)
smeshObj_18 = smeshObj_1.GroupOnGeom(Contact1,'Contact1',SMESH.NODE)
smeshObj_19 = smeshObj_1.GroupOnGeom(Contact2,'Contact2',SMESH.NODE)
smeshObj_20 = smeshObj_1.GroupOnGeom(Medium,'Medium',SMESH.NODE)
smeshObj_21 = smeshObj_1.GroupOnGeom(Air,'Air',SMESH.NODE)
smeshObj_1.RemoveGroupWithContents( smeshObj_7 )
smeshObj_1.RemoveGroupWithContents( smeshObj_8 )
smeshObj_1.RemoveGroupWithContents( smeshObj_9 )
smeshObj_1.RemoveGroupWithContents( smeshObj_10 )
smeshObj_1.RemoveGroupWithContents( smeshObj_11 )
smeshObj_1.RemoveGroupWithContents( smeshObj_17 )
smeshObj_1.RemoveGroupWithContents( smeshObj_18 )
smeshObj_1.RemoveGroupWithContents( smeshObj_19 )
smeshObj_1.RemoveGroupWithContents( smeshObj_20 )
smeshObj_1.RemoveGroupWithContents( smeshObj_21 )
smeshObj_1.RemoveGroupWithContents( smeshObj_12 )
smeshObj_1.RemoveGroupWithContents( smeshObj_13 )
smeshObj_1.RemoveGroupWithContents( smeshObj_14 )
smeshObj_1.RemoveGroupWithContents( smeshObj_15 )
smeshObj_1.RemoveGroupWithContents( smeshObj_16 )
smeshObj_22 = smeshObj_1.GroupOnGeom(OuterIsolation,'OuterIsolation',SMESH.FACE)
smeshObj_23 = smeshObj_1.GroupOnGeom(Contact1,'Contact1',SMESH.FACE)
smeshObj_24 = smeshObj_1.GroupOnGeom(Contact2,'Contact2',SMESH.FACE)
smeshObj_25 = smeshObj_1.GroupOnGeom(Medium,'Medium',SMESH.VOLUME)
smeshObj_26 = smeshObj_1.GroupOnGeom(Air,'Air',SMESH.VOLUME)
smeshObj_27 = smeshObj_1.GroupOnGeom(OuterIsolation,'OuterIsolation',SMESH.NODE)
smeshObj_28 = smeshObj_1.GroupOnGeom(Contact1,'Contact1',SMESH.NODE)
smeshObj_29 = smeshObj_1.GroupOnGeom(Contact2,'Contact2',SMESH.NODE)
smeshObj_30 = smeshObj_1.GroupOnGeom(Medium,'Medium',SMESH.NODE)
smeshObj_31 = smeshObj_1.GroupOnGeom(Air,'Air',SMESH.NODE)
isDone = smeshObj_1.Compute()
[ smeshObj_22, smeshObj_23, smeshObj_24, smeshObj_25, smeshObj_26, smeshObj_27, smeshObj_28, smeshObj_29, smeshObj_30, smeshObj_31 ] = smeshObj_1.GetGroups()
isDone = smeshObj_1.Compute()
[ smeshObj_22, smeshObj_23, smeshObj_24, smeshObj_25, smeshObj_26, smeshObj_27, smeshObj_28, smeshObj_29, smeshObj_30, smeshObj_31 ] = smeshObj_1.GetGroups()
smeshObj_1.Clear()
smeshObj_1.RemoveGroup( smeshObj_26 )
smeshObj_1.RemoveGroup( smeshObj_25 )
smeshObj_1.RemoveGroup( smeshObj_24 )
smeshObj_1.RemoveGroup( smeshObj_23 )
smeshObj_1.RemoveGroup( smeshObj_22 )
smeshObj_1.RemoveGroup( smeshObj_31 )
smeshObj_1.RemoveGroup( smeshObj_30 )
smeshObj_1.RemoveGroup( smeshObj_29 )
smeshObj_1.RemoveGroup( smeshObj_28 )
smeshObj_1.RemoveGroup( smeshObj_27 )
status = smeshObj_1.RemoveHypothesis(NETGEN_1D_2D_3D)
status = smeshObj_1.RemoveHypothesis(NETGEN_3D_Parameters_1)
Mesh_1 = smesh.Mesh(Cut_1)
status = Mesh_1.AddHypothesis(NETGEN_3D_Parameters_1)
status = Mesh_1.AddHypothesis(NETGEN_1D_2D_3D)
isDone = Mesh_1.Compute()
OuterIsolation_1 = Mesh_1.GroupOnGeom(OuterIsolation,'OuterIsolation',SMESH.FACE)
Contact1_1 = Mesh_1.GroupOnGeom(Contact1,'Contact1',SMESH.FACE)
Contact2_1 = Mesh_1.GroupOnGeom(Contact2,'Contact2',SMESH.FACE)
Medium_1 = Mesh_1.GroupOnGeom(Medium,'Medium',SMESH.VOLUME)
Air_1 = Mesh_1.GroupOnGeom(Air,'Air',SMESH.VOLUME)
OuterIsolation_2 = Mesh_1.GroupOnGeom(OuterIsolation,'OuterIsolation',SMESH.NODE)
Contact1_2 = Mesh_1.GroupOnGeom(Contact1,'Contact1',SMESH.NODE)
Contact2_2 = Mesh_1.GroupOnGeom(Contact2,'Contact2',SMESH.NODE)
Medium_2 = Mesh_1.GroupOnGeom(Medium,'Medium',SMESH.NODE)
Air_2 = Mesh_1.GroupOnGeom(Air,'Air',SMESH.NODE)
smesh.SetName(Mesh_1, 'Mesh_1')
try:
  Mesh_1.ExportMED(pwd + '/' + str(meshname) + '.med', 0, SMESH.MED_V2_2, 1, None ,1)
  pass
except:
  print 'ExportToMEDX() failed. Invalid file name?'

## some objects were removed
aStudyBuilder = theStudy.NewBuilder()
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_23))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_24))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_29))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_28))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_27))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_21))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_2))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_3))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_4))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_31))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_12))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_30))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_13))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_14))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_22))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_1.GetMesh()))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_26))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_25))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_16))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_15))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_6))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_5))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_19))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_20))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_8))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_9))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_7))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_17))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_18))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_10))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)
SO = theStudy.FindObjectIOR(theStudy.ConvertObjectToIOR(smeshObj_11))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)

## Set names of Mesh objects
smesh.SetName(Air_2, 'Air')
smesh.SetName(NETGEN_1D_2D_3D, 'NETGEN 1D-2D-3D')
smesh.SetName(Medium_2, 'Medium')
smesh.SetName(OuterIsolation_2, 'OuterIsolation')
smesh.SetName(Contact2_2, 'Contact2')
smesh.SetName(Medium_1, 'Medium')
smesh.SetName(Contact1_2, 'Contact1')
smesh.SetName(Air_1, 'Air')
smesh.SetName(NETGEN_3D_Parameters_1, 'NETGEN 3D Parameters_1')
smesh.SetName(Mesh_1.GetMesh(), 'Mesh_1')
smesh.SetName(Contact2_1, 'Contact2')
smesh.SetName(Contact1_1, 'Contact1')
smesh.SetName(OuterIsolation_1, 'OuterIsolation')


if salome.sg.hasDesktop():
  salome.sg.updateObjBrowser(True)
